program main
   use RFR, only: GENRFR
   ! USE PYPLOT_MODULE
   ! TYPE(PYPLOT) :: PLT
   INTEGER, PARAMETER :: N = 150
   INTEGER K1/10/, IS/125613/, NPR/450/
   INTEGER, ALLOCATABLE, DIMENSION (:) :: NBUC
   INTEGER, ALLOCATABLE, DIMENSION(:,:) :: NREFER
   REAL*8 X(N),Y(N),XM/110./,YM/110./,RMAX/10./,&
      EPSR/0.01/,CPROB/0.9/,RK1/1./,RFS/1.0/,RH2
   REAL*8, ALLOCATABLE, DIMENSION (:) :: RF, RK, S, RF0,&
      S0, RF1, S1
   NX=INT(XM/RMAX)
   NY=INT(YM/RMAX)
   NXY=NX*NY
   ALLOCATE(NBUC(N))
   NBUC=0
   ALLOCATE(NREFER(2, NXY))
   NREFER=0
   RH2=RK1*RK1
   K2=INT(RMAX*RMAX/RH2)
   IF(K2.GT.K1) GO TO 1
1  K1=K2
   ALLOCATE(RF(K1))
   RF(1)=RFS
   ALLOCATE(RK(K1))
   RK(1)=RK1
   ALLOCATE(S(K1))
   ALLOCATE(RF0(K1))
   ALLOCATE(S0(K1))
   ALLOCATE(RF1(K1))
   ALLOCATE(S1(K1))
   CALL GENRFR(N, X, Y, XM, YM, RMAX, K1, RF, RK,&
      S,RF0, S0, RF1, S1, EPSR, NBUC, NREFER, IS, NPR, CPROB)

   OPEN(UNIT=48,FILE='data.txt')
   DO I=1,N
      WRITE(48,*) X(I),Y(I)
   END DO
   CLOSE(48)

   CALL SYSTEM('gnuplot -p data_plot.plt')

   OPEN(UNIT=49,FILE='data2.txt')
   DO I=1,K1
      WRITE(49,*) RK(I),RF0(I)
   END DO
   CLOSE(49)

   CALL SYSTEM('gnuplot -p data_plot_2.plt')

   ! CALL PLT%INITIALIZE(GRID=.TRUE.,XLABEL='X',TITLE='TREES')
   ! CALL PLT%ADD_PLOT(X,Y,LABEL='TREES',LINESTYLE='b-o')
   ! CALL PLT%SAVEFIG('TREES.PNG',PYFILE='TREES.PY')
end program main
